### ISSUE TITLE
Another regular expression 

### ISSUE THREAD

**Issue by Maleeha** [OuhscBbmc/StatisticalComputing#10]
You don't have to look at it yet since i have not really spend time on the rest of it on my own but if you do find time to look at it, i am trying to finish the rest of it @wibeasley 

![expression](https://user-images.githubusercontent.com/5075490/67990079-c9f63200-fc02-11e9-9cbb-4c6d526e572b.png)

Thanks!

**Comment by Maleeha** [comment]
![02D97ED4-A784-440D-A71F-BF939D9BD06B](https://user-images.githubusercontent.com/5075490/67994216-1eed7480-fc12-11e9-8f83-758be6503f23.jpeg)

I think this does it but please let me know if there is a better way at your convenience 
@wibeasley

**Comment by wibeasley** [comment]
Hi @Maleeha, I'm happy to help.  Could you please include text version (that I can copy & paste) of
1. the subject/test strings (maybe at least 5 examples that span the range of input you'll face)
1. the regex pattern
1. your desired output

FYI, here's a lot more detailed advice for asking regex questions to people outside of your specific project:
1. https://meta.stackexchange.com/questions/222498/how-to-ask-a-good-regex-question
1. https://stackoverflow.com/tags/regex/info

Here's an example of one of my regex questions: https://stackoverflow.com/questions/55270833/regex-to-qualify-n

**Comment by Maleeha** [comment]
@wibeasley, I will post it in another issue in a way that you advised. Thank you!
