### ISSUE TITLE
Morning SCUG Question

### ISSUE THREAD

**Issue by Maleeha** [OuhscBbmc/StatisticalComputing#11]
@wibeasley 

Here is the work on Regex101. Please forgive the amateur pattern of regex here: 

[Example on regex101](https://regex101.com/r/BozQg9/3)

- Each cell here has exactly one match except the last cell which has 5 matches. 
- In-addition, in each cell, matches have also been captured except the last cell where only one match (out of 5) has been captured.
--------------------------------------------------------------------------------------------------------
I want to get it right:
-  Here is an example in R
```
pax <- c("asdgf2", "asd3", "bcdfs4", "zsdfs5", "asdfs6", "podf-podf-podf-podf-podf")

```
- Here is the pattern:

```
regex <- "(^\\D\\D\\D\\D)|-\\D\\D\\D\\D|(^\\D+)3"
```

- Here is the execution in R:

```
sub(regex, "PF",  pax)
gsub(regex, "PF",  pax)

```
- Here are the results with `sub`:

```
[1] "PFf2"                   "PF"                     "PFs4"                   "PFs5"                  
[5] "PFs6"                   "PF-podf-podf-podf-podf"
```
- ***Bottom-line: `sub` scans each cell and look at only the first match to replace it. Does not matter how much of the match was captured. Looks at matched and captured text the same way.***

- Here is an output with `gsub`
```
"PFf2"       "PF"         "PFs4"       "PFs5"       "PFs6"       "PFPFPFPFPF"
```
- ***Bottom-line: `gsub` scans each cell and look at all the matches to replace them and then replace each match with substitution.***

Thank you for your patience this morning

**Comment by wibeasley** [comment]
Also correct.
