### ISSUE TITLE
strategy for notification when a live dataset is changed

### ISSUE THREAD

**Issue by wibeasley** [OuhscBbmc/StatisticalComputing#7]
To @OuhscBbmc/dhswaiverpushpull, @mand9472 and others, 
@Maleeha [recently asked](https://github.com/OuhscBbmc/DhsWaiver/issues/177#issuecomment-268157666) "is there a possibility that a notification is sent to those who are responsible for the variables whenever they change on REDCap?".  For context, we have making some necessary changes to the REDCap database where people are entering live data.

I don't have a good solution for this recurring scenario, and I would appreciate suggestions how we might do it better.  I'm affected both as a producer (eg, the main person responsible for the DHS Waiver ferry) and as a consumer (eg, OSDH's ETO).  Here are the strategies that we currently (try to) employ:
1. Make changes to the data source in large, but infrequent batches.  I think a slow trickle of changes is harder (for the ~7 analysts on our project) to monitor.
1. Assign a questionnaire/instrument to as few analysts as possible, and encourage that analysts to feel ownership of that questionnaire and it's maintenance.  That also reduces the number of people affected; for example.
1. If only a few variables are changed, then `grep` the variable name and notify the analysts owning the files containing that variable name (eg `$ grep -rl "iss_assigned_date" ~/Bbmc/DhsWaiver`).
1. If broad changes occur, then make a general announcement and request that everyone check their reports against the development version of the database/ferry (eg, the issue called ["prospectively check your reports against the v1.1 ferry"](https://github.com/OuhscBbmc/DhsWaiver/issues/160)).

    Th recent change affected all most all the important variables (eg, the group assignment), so I assigned it to almost everyone.  I didn't assume anyone's reports would be immune.

    ![image](https://cloud.githubusercontent.com/assets/1372890/21359854/2cd1b112-c6a3-11e6-94f2-6ebe067c9986.png)

1. This transition from the old database to the new database is tough, and we avoid doing it when reports need to be run.  I know the proper software engineering strategy is to branch the repo, and eventually merge it into the master after everything's tested.  Although I [do this for proper R packages](https://github.com/OuhscBbmc/REDCapR/network),  I've been reluctant to branch repos that mainly hold analysis code and reports.

*spun off of #177* (cc: @andkov & @aggie-dba)

**Comment by Maleeha** [comment]
Thank you @wibeasley.  .
