### ISSUE TITLE
Regular expression problem

### ISSUE THREAD

**Issue by Maleeha** [OuhscBbmc/StatisticalComputing#8]
I have the following regular expression to capture `$`, `,`, `.` and digits after period.

```
^(\$)\d*(,)\d*(.)(\d*)
```
It is for the following character variable. I am giving one value here:
```
$34,000.00
```
I want to get rid of all the captured groups. What do i substitute it with in the following statement.

```
dplyr::mutate(
    income = as.numeric(sub(regex, "", annual_income))
  )
```
@wibeasley ... I am not able to tag anyone else.

Thanks!

**Comment by wibeasley** [comment]
how's this?

```r
> source <- "$34,000.00"

> gsub("[$,\\.]", "", source)
[1] "3400000"
```

**Comment by Maleeha** [comment]
What if i want to match the two 0's after the period as well?
@wibeasley

**Comment by Maleeha** [comment]
Okay this worked:
```
> source <- "$34,000.00"
> gsub("[$]|[,]|[\.][0-9]{2}", "", source)
[1] "34000"
```
